<a href="https://colab.research.google.com/github/WhiteC0der/Machine_Learning/blob/main/Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#data encoding >> converting categorical data into numerical data
#Nominal/OHE
#label and ordinal encoding
#Tagert guided ordinal encoding

In [ ]:
#Nominal/OHE >> binary vector for each categories


In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.DataFrame({'status': ['single', 'married', 'separated', 'single', 'married']})
df

status
0     single
1    married
2  separated
3     single
4    married

In [ ]:
encoder =OneHotEncoder()

In [ ]:
encoder

OneHotEncoder()

In [ ]:
encoded= encoder.fit_transform(df[['status']]).toarray()

In [ ]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [ ]:
encoded_df =pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [ ]:
encoded_df


status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0

In [ ]:
# new data
encoder.transform([['married']]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [ ]:
# n --> n-1 attributes can be reduce

In [ ]:
df

status
0     single
1    married
2  separated
3     single
4    married

In [ ]:
pd.concat([df,encoded_df],axis=1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0

In [ ]:
pd.get_dummies(df,columns=['status'])

status_married  status_separated  status_single
0           False             False           True
1            True             False          False
2           False              True          False
3           False             False           True
4            True             False          False

In [ ]:
import seaborn as sns
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
#label encoding>> assigns unique label to the categories

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder=LabelEncoder()

In [ ]:
label_encoder.fit_transform(df[['status']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [ ]:
label_encoder.transform(['separated'])

array([1])

In [55]:
#ordinal encoding

#High school: 1
#graduate: 2
#pg:3
#phd:4

In [56]:
from sklearn.preprocessing import OrdinalEncoder

In [57]:
df = pd.DataFrame({"qualification": ["HS", "GR", "PG", "PhD", "HS", "HS", "PhD","PG" ]})

In [58]:
df

qualification
0            HS
1            GR
2            PG
3           PhD
4            HS
5            HS
6           PhD
7            PG

In [59]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PhD"]])

In [60]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [0.],
       [3.],
       [2.]])

In [61]:
#new data
encoder.transform([['PG']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [62]:
#Target guided ordinal encoding
#relationship with target variable
# A  lot of unique categories
#Replace the category with the mean and median of respective group target

In [63]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [64]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [65]:
mean_price

{'breakfast': 153.33333333333334, 'dinner': 156.33333333333334, 'lunch': 135.0}

In [66]:
df['time_encoded'] = df['time'].map(mean_price)

In [67]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [69]:
df= sns.load_dataset('tips')

In [70]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [79]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
encoder = OneHotEncoder()
encoder.fit_transform(df[['day']]).toarray()

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [83]:
df_encoded = pd.DataFrame(encoder.fit_transform(df[['day']]).toarray(),columns=encoder.get_feature_names_out())

In [84]:
pd.concat([df,df_encoded],axis=1)

total_bill   tip     sex smoker  ... day_Fri day_Sat  day_Sun  day_Thur
0         16.99  1.01  Female     No  ...     0.0     0.0      1.0       0.0
1         10.34  1.66    Male     No  ...     0.0     0.0      1.0       0.0
2         21.01  3.50    Male     No  ...     0.0     0.0      1.0       0.0
3         23.68  3.31    Male     No  ...     0.0     0.0      1.0       0.0
4         24.59  3.61  Female     No  ...     0.0     0.0      1.0       0.0
..          ...   ...     ...    ...  ...     ...     ...      ...       ...
239       29.03  5.92    Male     No  ...     0.0     1.0      0.0       0.0
240       27.18  2.00  Female    Yes  ...     0.0     1.0      0.0       0.0
241       22.67  2.00    Male    Yes  ...     0.0     1.0      0.0       0.0
242       17.82  1.75    Male     No  ...     0.0     1.0      0.0       0.0
243       18.78  3.00  Female     No  ...     0.0     0.0      0.0       1.0

[244 rows x 11 columns]

In [85]:
from sklearn.preprocessing import LabelEncoder

In [86]:
encoder = LabelEncoder()

In [90]:
encoded_days = encoder.fit_transform(df['day'])
encoded_days

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [91]:
pd.DataFrame(encoded_days,columns=['encoded_days'])

encoded_days
0               2
1               2
2               2
3               2
4               2
..            ...
239             1
240             1
241             1
242             1
243             3

[244 rows x 1 columns]

In [93]:
pd.concat([df,pd.DataFrame(encoded_days,columns=['encoded_days'])],axis=1)

total_bill   tip     sex smoker   day    time  size  encoded_days
0         16.99  1.01  Female     No   Sun  Dinner     2             2
1         10.34  1.66    Male     No   Sun  Dinner     3             2
2         21.01  3.50    Male     No   Sun  Dinner     3             2
3         23.68  3.31    Male     No   Sun  Dinner     2             2
4         24.59  3.61  Female     No   Sun  Dinner     4             2
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3             1
240       27.18  2.00  Female    Yes   Sat  Dinner     2             1
241       22.67  2.00    Male    Yes   Sat  Dinner     2             1
242       17.82  1.75    Male     No   Sat  Dinner     2             1
243       18.78  3.00  Female     No  Thur  Dinner     2             3

[244 rows x 8 columns]

In [94]:
from sklearn.preprocessing import OrdinalEncoder

In [95]:
encoder = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])

In [96]:
encoder.fit_transform(df[['day']])

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],

In [108]:
mean=df.groupby('day')['size'].mean().to_dict()

/tmp/ipython-input-2724143795.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean=df.groupby('day')['size'].mean().to_dict()


In [109]:
df['encoded_day']= df['day'].map(mean)

In [107]:
df

total_bill   tip     sex smoker   day    time  size encoded_day
0         16.99  1.01  Female     No   Sun  Dinner     2    2.842105
1         10.34  1.66    Male     No   Sun  Dinner     3    2.842105
2         21.01  3.50    Male     No   Sun  Dinner     3    2.842105
3         23.68  3.31    Male     No   Sun  Dinner     2    2.842105
4         24.59  3.61  Female     No   Sun  Dinner     4    2.842105
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3    2.517241
240       27.18  2.00  Female    Yes   Sat  Dinner     2    2.517241
241       22.67  2.00    Male    Yes   Sat  Dinner     2    2.517241
242       17.82  1.75    Male     No   Sat  Dinner     2    2.517241
243       18.78  3.00  Female     No  Thur  Dinner     2    2.451613

[244 rows x 8 columns]